
version: "2"

services:
  bitcoin_ticker_exporter:
    image: maven:3.3.3-jdk-8-onbuild
    working_dir: /usr/src/app
    ports:
      - "9999:9999"
    volumes:
      - .:/usr/src/app
    command: mvn install clean package exec:java
    restart: always

  prometheus:
    image: prom/prometheus
    links:
      - bitcoin_ticker_exporter
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: -storage.local.retention=2160h -config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -web.console.libraries=/etc/prometheus/console_libraries -web.console.templates=/etc/prometheus/consoles
    restart: always
